import { supabase } from "@/integrations/supabase/client";

// Database types are generated by Supabase; cast until the generated file is refreshed after applying catalog-upgrade.sql.
const db = supabase as any;

export type ImportBatch = { id: string; batch_name: string; source_file_name?: string | null; product_count: number; created_at: string };

const automaticName = () => new Intl.DateTimeFormat("en", { month: "long", year: "numeric" }).format(new Date()) + " Collection";

export const createImportBatch = async (sourceFileName: string, name?: string): Promise<ImportBatch> => {
  const { data: session } = await supabase.auth.getSession();
  if (!session.session?.user) throw new Error("You must be logged in to import products.");
  const { data, error } = await db.from("product_import_batches").insert({
    user_id: session.session.user.id, batch_name: name?.trim() || automaticName(), source_file_name: sourceFileName
  }).select().single();
  if (error) throw error;
  return data as ImportBatch;
};

export const getImportBatches = async (): Promise<ImportBatch[]> => {
  const { data, error } = await db.from("product_import_batches").select("*").order("created_at", { ascending: false });
  if (error) throw error;
  return (data || []) as ImportBatch[];
};

export const updateImportBatchCount = async (id: string, productCount: number) => {
  const { error } = await db.from("product_import_batches").update({ product_count: productCount }).eq("id", id);
  if (error) throw error;
};
