// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fegofteqoocvsnuuemkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlZ29mdGVxb29jdnNudXVlbWtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5Mjk0NzEsImV4cCI6MjA1ODUwNTQ3MX0.sXEBP1vrLbtF-CV91M8lCZ654-zlKFwvfzd5KuH95zo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);